; ============================================================
; AdvancedPedStudio - Saved Customized Peds
; Last Updated: 2026-09-03 22:15:00
; ============================================================

[Purple Stripper Test]
FriendlyName = Purple Stripper Test
Model = s_f_y_stripper_01
Option = d
MovementStyle = move_f@sexy
AnimationType = Animation
AnimDict = mini@strip_club@pole_dance@pole_dance1
AnimClip = base
Scenario = 
SavedAt = 2026-09-01 22:09:44
Component_0 = 1,1
Component_0_Drawable = 1
Component_0_Texture = 1
Component_1 = 0,0
Component_1_Drawable = 0
Component_1_Texture = 0
Component_2 = 2,0
Component_2_Drawable = 2
Component_2_Texture = 0
Component_3 = 1,2
Component_3_Drawable = 1
Component_3_Texture = 2
Component_4 = 1,2
Component_4_Drawable = 1
Component_4_Texture = 2
Component_5 = 0,0
Component_5_Drawable = 0
Component_5_Texture = 0
Component_6 = 0,0
Component_6_Drawable = 0
Component_6_Texture = 0
Component_7 = 0,0
Component_7_Drawable = 0
Component_7_Texture = 0
Component_8 = 0,2
Component_8_Drawable = 0
Component_8_Texture = 2
Component_9 = 1,0
Component_9_Drawable = 1
Component_9_Texture = 0
Component_10 = 0,0
Component_10_Drawable = 0
Component_10_Texture = 0
Component_11 = 0,2
Component_11_Drawable = 0
Component_11_Texture = 2
Prop_0 = -1,0
Prop_0_Index = -1
Prop_0_Texture = 0
Prop_1 = -1,0
Prop_1_Index = -1
Prop_1_Texture = 0
Prop_2 = -1,0
Prop_2_Index = -1
Prop_2_Texture = 0
Prop_6 = -1,0
Prop_6_Index = -1
Prop_6_Texture = 0
Prop_7 = -1,0
Prop_7_Index = -1
Prop_7_Texture = 0

[Black Lingerie Blonde Stripper]
FriendlyName = Black Lingerie Blonde Stripper
Model = s_f_y_stripper_01
Option = d
MovementStyle = move_f@posh@
AnimationType = Animation
AnimDict = anim@amb@nightclub@mini@dance@dance_solo@female@var_a@
AnimClip = med_center
Scenario = 
SavedAt = 2026-09-01 23:33:09
Component_0 = 0,1
Component_0_Drawable = 0
Component_0_Texture = 1
Component_1 = 0,0
Component_1_Drawable = 0
Component_1_Texture = 0
Component_2 = 2,0
Component_2_Drawable = 2
Component_2_Texture = 0
Component_3 = 0,1
Component_3_Drawable = 0
Component_3_Texture = 1
Component_4 = 1,1
Component_4_Drawable = 1
Component_4_Texture = 1
Component_5 = 0,0
Component_5_Drawable = 0
Component_5_Texture = 0
Component_6 = 0,0
Component_6_Drawable = 0
Component_6_Texture = 0
Component_7 = 0,0
Component_7_Drawable = 0
Component_7_Texture = 0
Component_8 = 1,0
Component_8_Drawable = 1
Component_8_Texture = 0
Component_9 = 0,0
Component_9_Drawable = 0
Component_9_Texture = 0
Component_10 = 0,0
Component_10_Drawable = 0
Component_10_Texture = 0
Component_11 = 1,2
Component_11_Drawable = 1
Component_11_Texture = 2
Prop_0 = -1,0
Prop_0_Index = -1
Prop_0_Texture = 0
Prop_1 = -1,0
Prop_1_Index = -1
Prop_1_Texture = 0
Prop_2 = -1,0
Prop_2_Index = -1
Prop_2_Texture = 0
Prop_6 = -1,0
Prop_6_Index = -1
Prop_6_Texture = 0
Prop_7 = -1,0
Prop_7_Index = -1
Prop_7_Texture = 0

[Test]
FriendlyName = Test
Model = s_f_y_stripper_02
Option = a
MovementStyle = move_f@heels@c
AnimationType = Scenario
AnimDict = 
AnimClip = 
Scenario = WORLD_HUMAN_PARTYING
SavedAt = 2026-09-01 23:51:18
Component_0 = 1,1
Component_0_Drawable = 1
Component_0_Texture = 1
Component_1 = 0,0
Component_1_Drawable = 0
Component_1_Texture = 0
Component_2 = 0,2
Component_2_Drawable = 0
Component_2_Texture = 2
Component_3 = 0,2
Component_3_Drawable = 0
Component_3_Texture = 2
Component_4 = 0,1
Component_4_Drawable = 0
Component_4_Texture = 1
Component_5 = 0,0
Component_5_Drawable = 0
Component_5_Texture = 0
Component_6 = 4,0
Component_6_Drawable = 4
Component_6_Texture = 0
Component_7 = 0,0
Component_7_Drawable = 0
Component_7_Texture = 0
Component_8 = 0,4
Component_8_Drawable = 0
Component_8_Texture = 4
Component_9 = 1,0
Component_9_Drawable = 1
Component_9_Texture = 0
Component_10 = 0,0
Component_10_Drawable = 0
Component_10_Texture = 0
Component_11 = 0,0
Component_11_Drawable = 0
Component_11_Texture = 0
Prop_0 = -1,0
Prop_0_Index = -1
Prop_0_Texture = 0
Prop_1 = -1,0
Prop_1_Index = -1
Prop_1_Texture = 0
Prop_2 = -1,0
Prop_2_Index = -1
Prop_2_Texture = 0
Prop_6 = -1,0
Prop_6_Index = -1
Prop_6_Texture = 0
Prop_7 = -1,0
Prop_7_Index = -1
Prop_7_Texture = 0
